# Generated by Django 5.0 on 2023-12-17 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.order')),
            ],
        ),
    ]
