# Generated by Django 5.0 on 2023-12-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='PP', upload_to=''),
            preserve_default=False,
        ),
    ]
